# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c325bed82b271a021d87712f88efe7d17b9723ccef374ec141d84e15804cd05b7a632d98ce9c829701efc974007c4b3cc68e767ccf549442df13caaa6075f4de

test:
  secret_key_base: 558abc192556412e6edfbf667c32a2b9374210cb428d2bd3a36eca1913798331bf6e9cb4d622d5d7a8e175006cb9b7f0bf2d59c62cc9f3b228c78c93b22fd8a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
